name: Setup Node.js
description: Setup Node.js and pnpm

inputs:
  registry-url:
    # ref: https://github.com/actions/setup-node/blob/1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a/action.yml#L18C5-L18C176
    description: "Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN."
    required: false
    default: ""
  node-version-file:
    description: "Path to a file containing the Node.js version to use. If not set, defaults to '.node-version'."
    required: false
    default: ".node-version"
  node-version:
    description: "Details the Node.js version to use. If not set, it will read from the file specified in 'node-version-file'."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        run_install: false

    - name: Get pnpm store path
      id: pnpm-store
      shell: bash
      run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Setup Node.js with node version
      if: ${{ inputs.node-version != '' }}
      id: setup-node-with-version
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Setup Node.js with node version file
      if: ${{ steps.setup-node-with-version.outcome == 'skipped' }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ${{ inputs.node-version-file }}
        registry-url: ${{ inputs.registry-url }}

    - name: Restore pnpm cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ steps.pnpm-store.outputs.store_path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Save pnpm cache if main branch
      if: github.ref_name == 'main'
      id: save-pnpm-cache
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ steps.pnpm-store.outputs.store_path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
