name: Publish to npm

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  release:
    name: Release
    if: github.repository == 'sushichan044/template-ts-lib-polyrepo'
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Setup latest npm to use trusted publish
        run: |
          npm install -g npm@latest

      - name: Release
        run: pnpm exec release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
